name: v_dash_mobile
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

# Supported Flutter: 3.47.5
environment:
  sdk: "3.13.4"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: 1.0.9
  flutter_bloc: 9.1.1
  go_router: 18.0.1
  envied: 1.3.9
  bloc: 9.2.1
  equatable: 2.1.0
  dio: 5.11.1
  fpdart: 1.2.0
  get_it: 9.3.0
  easy_localization: 3.0.8
  hive_ce: 2.20.0
  hive_ce_flutter: 2.3.4
  shared_preferences: 2.5.5

dev_dependencies:
  envied_generator: 1.3.9
  hive_ce_generator: 1.11.3
  build_runner: 2.16.1
  flutter_launcher_icons: 0.14.4
  flutter_test:
    sdk: flutter

  flutter_lints: 6.0.0
  change_app_package_name: 1.5.0

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/app_icon/icon.png"
  adaptapive_icon_background: "#ffffff"

flutter:
  assets:
    - assets/images/
    - assets/translations/
  uses-material-design: true
